#include <cmath>
#include "player_character.h"
#include <SFML/Graphics/RenderWindow.hpp>
#include <iostream>
#include <SFML/Window/Keyboard.hpp>
#include <sstream>
#include "game.h"
#include <box2d/box2d.h>
#include "contact_listener.h"